apiVersion: 1

datasources:
  - name: Energy OEE DB
    uid: efip9ykqyp534e
    type: postgres
    access: proxy
    url: db:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    isDefault: true
    editable: true
    editable: true